require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5

  Exclude:
    - 'bin/*'
    - 'db/schema.rb'

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
